import { WorkspacePermission, WorkspaceRole } from './types';

export const WORKSPACE_ROLE_PERMISSIONS: Record<
  WorkspaceRole,
  Record<WorkspacePermission, boolean>
> = {
  OWNER: {
    'workspace:view': true,
    'workspace:update': true,
    'workspace:delete': true,
    'member:read': true,
    'member:invite': true,
    'member:update_role': true,
    'member:remove': true,
    'audit:read': true,
    'file:view': true,
    'file:upload': true,
    'file:download': true,
    'file:update': true,
    'file:delete': true,
    'quota:read': true,
    'quota:update': true,
  },
  ADMIN: {
    'workspace:view': true,
    'workspace:update': true,
    'workspace:delete': false,
    'member:read': true,
    'member:invite': true,
    'member:update_role': true,
    'member:remove': true,
    'audit:read': true,
    'file:view': true,
    'file:upload': true,
    'file:download': true,
    'file:update': true,
    'file:delete': true,
    'quota:read': true,
    'quota:update': true,
  },
  EDITOR: {
    'workspace:view': true,
    'workspace:update': false,
    'workspace:delete': false,
    'member:read': false,
    'member:invite': false,
    'member:update_role': false,
    'member:remove': false,
    'audit:read': false,
    'file:view': true,
    'file:upload': true,
    'file:download': true,
    'file:update': true,
    'file:delete': true,
    'quota:read': true,
    'quota:update': false,
  },
  VIEWER: {
    'workspace:view': true,
    'workspace:update': false,
    'workspace:delete': false,
    'member:read': false,
    'member:invite': false,
    'member:update_role': false,
    'member:remove': false,
    'audit:read': false,
    'file:view': true,
    'file:upload': false,
    'file:download': true,
    'file:update': false,
    'file:delete': false,
    'quota:read': true,
    'quota:update': false,
  },
  GUEST: {
    'workspace:view': true,
    'workspace:update': false,
    'workspace:delete': false,
    'member:read': false,
    'member:invite': false,
    'member:update_role': false,
    'member:remove': false,
    'audit:read': false,
    'file:view': true,
    'file:upload': false,
    'file:download': true,
    'file:update': false,
    'file:delete': false,
    'quota:read': true,
    'quota:update': false,
  },
};

export function hasWorkspacePermission(
  role: WorkspaceRole,
  permission: WorkspacePermission,
): boolean {
  return WORKSPACE_ROLE_PERMISSIONS[role]?.[permission] === true;
}
